#ifndef __MAIN_H
#define __MAIN_H

#include "stm32f7xx_hal.h"

// ==== GPIO PINS ====

// X Stepper
#define X_DIR_Pin GPIO_PIN_0
#define X_DIR_GPIO_Port GPIOA

#define X_STEP_Pin GPIO_PIN_1
#define X_STEP_GPIO_Port GPIOA

// Y Stepper
#define Y_DIR_Pin GPIO_PIN_2
#define Y_DIR_GPIO_Port GPIOA

#define Y_STEP_Pin GPIO_PIN_3
#define Y_STEP_GPIO_Port GPIOA

// ==== HANDLES ====
extern UART_HandleTypeDef huart1;
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim6;

// ==== INIT FUNCTIONS (generated by CubeMX) ====
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_USART1_UART_Init(void);
void MX_TIM3_Init(void);
void MX_TIM6_Init(void);

#endif